# Generated by Django 2.0.3 on 2018-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='start_period',
            new_name='newstart_period',
        ),
        migrations.RemoveField(
            model_name='user',
            name='end_period',
        ),
        migrations.AddField(
            model_name='user',
            name='newend_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
