# Generated by Django 2.0.3 on 2018-03-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0002_auto_20180331_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tariff_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='choose.Tariff', verbose_name='Тариф'),
        ),
    ]
