# Generated by Django 2.0.3 on 2018-03-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0004_auto_20180331_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='newend_period',
            new_name='end_period',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='newstart_period',
            new_name='start_period',
        ),
    ]
